"""add task indents col

Revision ID: 633a2e56faff
Revises: 
Create Date: 2023-06-28 21:25:44.220904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "633a2e56faff"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("indents", sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE task SET indents = 0")
    op.alter_column("users", "is_admin", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "indents")
    # ### end Alembic commands ###
